<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="fr" sourcelanguage="en">
<context>
    <name>@default</name>
    <message>
        <location filename="../../qgis_plugin_tools/tools/custom_logging.py" line="63"/>
        <source>Due to memory limitations on this machine, the plugin {} can not handle the full log</source>
        <translation>Pardon?</translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="53"/>
        <source>Tableau des fichiers d&apos;ITV importÃ©s</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_geom_obs_algorithm.py" line="38"/>
        <source>Tableau des tronÃ§ons d&apos;ITV</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="69"/>
        <source>Tableau des observations d&apos;ITV</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="77"/>
        <source>Tableau des regards d&apos;ITV</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_geom_regard_algorithm.py" line="49"/>
        <source>Couche des gÃ©omÃ©tries de regards</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_geom_obs_algorithm.py" line="46"/>
        <source>Couche des gÃ©omÃ©tries de tronÃ§ons</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_geom_obs_algorithm.py" line="62"/>
        <source>Couche des gÃ©omÃ©tries d&apos;observations</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/config_project_algorithm.py" line="108"/>
        <source>Couche des regards gÃ©olocalisÃ©s</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/config_project_algorithm.py" line="362"/>
        <source>Create project variables according to layers.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/config_project_algorithm.py" line="368"/>
        <source>05 Project configuration</source>
        <translation>05 Configuration du projet</translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/load_postgis_layers_algorithm.py" line="144"/>
        <source>Configuration</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_geom_segment_algorithm.py" line="71"/>
        <source>Number of segment created</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_geom_obs_algorithm.py" line="182"/>
        <source>* ERROR: Expression %s has eval error: %s</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_geom_obs_algorithm.py" line="222"/>
        <source>* ERREUR: lors de l&apos;enregistrement des regards %s</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_geom_obs_algorithm.py" line="225"/>
        <source>* ERROR: Commit %s.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_geom_segment_algorithm.py" line="344"/>
        <source>* ERREUR: Aucune gÃ©omÃ©trie de tronÃ§on</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_geom_segment_algorithm.py" line="381"/>
        <source>Generate segments from manholes.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_geom_segment_algorithm.py" line="387"/>
        <source>05 Create segment geometries</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_geom_obs_algorithm.py" line="238"/>
        <source>Drain Sewer Visual Inspection data</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_geom_regard_algorithm.py" line="32"/>
        <source>Couche des regards Ã&#xa0; importer</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_geom_regard_algorithm.py" line="39"/>
        <source>Champs du nom des regards Ã&#xa0; conserver</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_geom_regard_algorithm.py" line="57"/>
        <source>Number of imported man holes</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_geom_regard_algorithm.py" line="105"/>
        <source>It will import the geometry and the specified field into the layer &quot;geom_regard&quot;.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_geom_regard_algorithm.py" line="111"/>
        <source>10 Import des gÃ©omÃ©tries de regards</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_data_model_algorithm.py" line="58"/>
        <source>Coordinate Reference System</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/load_postgis_layers_algorithm.py" line="84"/>
        <source>Output layers</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_data_model_algorithm.py" line="119"/>
        <source>* ERROR: Can&apos;t load CSV {}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_data_model_algorithm.py" line="132"/>
        <source>* ERROR while creating fields in layer &quot;{}&quot;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_data_model_algorithm.py" line="165"/>
        <source>* ERROR while exporting the layer to &quot;{}&quot;:&quot;{}&quot;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/load_postgis_layers_algorithm.py" line="122"/>
        <source>* ERROR: Can&apos;t load table &quot;{}&quot; in URI &quot;{}&quot;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_data_model_algorithm.py" line="266"/>
        <source>* ERROR: Can&apos;t load layer {} in {}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_data_model_algorithm.py" line="309"/>
        <source>01 Create geopackage data model</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_data_model_algorithm.py" line="312"/>
        <source>Geopackage file</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_data_model_algorithm.py" line="322"/>
        <source>Create the data model with a new geopackage.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_data_model_algorithm.py" line="331"/>
        <source>00 Create postgis data model</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/load_postgis_layers_algorithm.py" line="66"/>
        <source>Database (connection name)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/load_postgis_layers_algorithm.py" line="75"/>
        <source>Schema (schema name)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_data_model_algorithm.py" line="356"/>
        <source>Create the data model in a PostGIS schema.
Be careful, all these tables are going to be replaced: {} and the view &quot;{}&quot; in the given schema.
The given schema must exist before.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/provider.py" line="65"/>
        <source>Drain sewer visual inspection</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/load_postgis_layers_algorithm.py" line="63"/>
        <source>00 Load postgis layers</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/load_postgis_layers_algorithm.py" line="98"/>
        <source>* ERROR while getting database &quot;{}&quot;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="46"/>
        <source>Fichier d&apos;ITV</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_geom_obs_algorithm.py" line="70"/>
        <source>SuccÃ¨s</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="96"/>
        <source>* ERREUR: 1 fichier a la fois %s.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="100"/>
        <source>* ERREUR: %s n&apos;existe pas.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="125"/>
        <source>* ERREUR: le fichier %s n&apos;a pas ete lu correctement.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="146"/>
        <source>* ERREUR: le fichier %s a deja ete lu</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="161"/>
        <source>* ERREUR: le fichier %s semble deja avoir ete lu</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="388"/>
        <source>id_regard1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="391"/>
        <source>id_regard2</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="395"/>
        <source>id_regard3</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="410"/>
        <source>* ERREUR dans le fichier : le champs de tronÃ§on &quot;%s&quot; est inconnue</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="418"/>
        <source>* ERREUR dans le fichier : le champs de tronÃ§on &quot;%s&quot; est numÃ©rique mais pas la valeur &quot;%s&quot;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="433"/>
        <source>* ERREUR dans le fichier : le champs d&apos;observation &quot;%s&quot; est inconnue</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="441"/>
        <source>* ERREUR dans le fichier : le champs d&apos;observation &quot;%s&quot; est numÃ©rique mais pas la valeur &quot;%s&quot;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="456"/>
        <source>* ERREUR dans le fichier : le champs de regard &quot;%s&quot; est inconnue</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="464"/>
        <source>* ERREUR dans le fichier : le champs de regard &quot;%s&quot; est numÃ©rique mais pas la valeur &quot;%s&quot;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="484"/>
        <source>* ERREUR: lors de l&apos;enregistrement du fichier %s</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="513"/>
        <source>* ERREUR: lors de l&apos;enregistrement des troncon %s</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="539"/>
        <source>* ERREUR: lors de l&apos;enregistrement des observations %s</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="575"/>
        <source>It will import Drain Sewer Visual Inspection data into the geopackage.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/import_dsvi_file_algorithm.py" line="581"/>
        <source>00 Import DSVI data</source>
        <translation>00 Import des données ITV</translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_geom_obs_algorithm.py" line="54"/>
        <source>Tableau des observations</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_geom_obs_algorithm.py" line="108"/>
        <source>* ERROR: No troncon geometries</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_geom_obs_algorithm.py" line="142"/>
        <source>* ERROR: No observations to geolocalize found</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../processing_algorithms/create_geom_obs_algorithm.py" line="235"/>
        <source>10 Create observations geometries</source>
        <translation>10 Création des observations géométriques</translation>
    </message>
</context>
</TS>
